### ISSUE TITLE
Incorrect release date

### ISSUE THREAD

**Issue by yephny** [UweTrottmann/SeriesGuide#848]
**Describe the bug**
There are some cases where the release date for a movie is wrong.

**To Reproduce**
1. Search for Le Samouraï. The search result will show 1972 as its release date.
2. Open the movie's page. It will say 1997.
3. Go to the movie's [TMDB page](https://www.themoviedb.org/movie/5511-le-samoura). You will see that it was released in 1967. 

**Expected behavior**
The release date info should always be correct and consistent.

**Screenshots**
Le Samouraï in [search results](https://i.imgur.com/qNcweeF.png) versus [the movie page](https://i.imgur.com/1b5AP4I.png).

**Smartphone**
v.63.1.0, Android 10

**Comment by UweTrottmann** [comment]
The release date depends on the country you have selected. Tap on the globe symbol to change it.

**Comment by yephny** [comment]
@UweTrottmann It is set to the US. The movie is known as Le Samouraï (1967). Still, it doesn't account for the inconsistency.

**Comment by yephny** [comment]
Perhaps the issue needs to remain open.

**Comment by UweTrottmann** [comment]
It appears the movie has two theatrical release dates for the US. SeriesGuide currently picks the first one returned by TMDB, which apparently is not always ordered by oldest first.

With the next update SeriesGuide will pick the oldest theatrical release (if available): c6b4c7f9

Note: for search results TMDB provides the release date based on region. It appears to also use the oldest theatrical one, so hopefully it will always match with the next update.

**Comment by UweTrottmann** [comment]
Thanks for reporting! This should be fixed with the next update.

**Comment by yephny** [comment]
The issue persists.

See [C.R.A.Z.Y.](https://www.themoviedb.org/movie/11421).

![screenshot](https://i.imgur.com/qHwDpSC.png)

**Comment by UweTrottmann** [comment]
Nope, the app works correctly, assuming you are using United States as the region for movies: https://www.themoviedb.org/movie/11421-c-r-a-z-y/releases

**Comment by yephny** [comment]
Does it make sense, though? It throws me off when I see 2022 for a movie that came out in 2005. Is there a way to show the first release on TMDB regardless of region?

**Comment by UweTrottmann** [comment]
> Is there a way to show the first release on TMDB regardless of region?

Sorry, SeriesGuide can not do this right now. So this is a feature request then.
